import { doctors } from "@/app/site-data";

export function AppointmentWizard() {
  return <form className="appointment-wizard" action="/api/appointment-requests" method="post"><ol className="wizard-progress" aria-label="Pasos de la solicitud">{["Atención", "Profesional", "Cobertura", "Fecha y horario", "Tus datos", "Confirmación"].map((label, index) => <li className="active" key={label}><span>{index + 1}</span><b>{label}</b></li>)}</ol>
    <fieldset><legend>1. Atención y profesional</legend><div className="field-grid"><label>Tipo de atención<select name="careType" defaultValue="first_consultation"><option value="first_consultation">Primera consulta</option><option value="follow_up">Consulta de control</option><option value="study">Estudio</option><option value="other_service">Otra prestación</option></select></label><label>Profesional <small>Opcional</small><select name="doctorName" defaultValue=""><option value="">Primer médico disponible</option>{doctors.map((doctor) => <option key={doctor.name} value={doctor.name}>{doctor.name}</option>)}</select></label></div><input type="hidden" name="firstAvailable" value="true" /></fieldset>
    <fieldset><legend>2. Cobertura</legend><div className="field-grid"><label>Tipo<select name="coverageKind" defaultValue="particular"><option value="particular">Particular</option><option value="obra_social">Obra social</option><option value="prepaga">Prepaga</option></select></label><label>Empresa <small>Opcional</small><input name="coverageName" /></label><label>Plan <small>Opcional</small><input name="coveragePlan" /></label><label>Número de afiliado <small>Opcional</small><input name="memberNumber" /></label></div></fieldset>
    <fieldset><legend>3. Fecha y horario</legend><p className="wizard-help">Indicá tu preferencia; la clínica confirmará la disponibilidad.</p><div className="preference-grid"><div><b>Opción principal</b><label>Fecha<input name="preferredDate" type="date" /></label><label>Horario<input name="preferredTimeBand" type="time" step="900" /></label></div><div><b>Segunda alternativa</b><label>Fecha<input name="alternativeDate" type="date" /></label><label>Horario<input name="alternativeTimeBand" type="time" step="900" /></label></div><div><b>Tercera alternativa</b><label>Fecha<input name="thirdDate" type="date" /></label><label>Horario<input name="thirdTimeBand" type="time" step="900" /></label></div></div></fieldset>
    <fieldset><legend>4. Tus datos</legend><div className="field-grid"><label>Nombre<input name="firstName" required /></label><label>Apellido<input name="lastName" required /></label><label>DNI<input name="dni" inputMode="numeric" pattern="[0-9]{7,9}" required /></label><label>Teléfono<input name="phone" inputMode="tel" required /></label><label>Correo electrónico <small>Opcional</small><input name="email" type="email" /></label><label>Fecha de nacimiento <small>Opcional</small><input name="birthDate" type="date" /></label></div><input type="hidden" name="returningPatient" value="false" /></fieldset>
    <div className="wizard-actions"><button className="button" type="submit">Enviar solicitud</button></div></form>;
}
