/* eslint-disable @next/next/no-img-element */
import { AppointmentWizard } from "@/components/appointment-wizard";
import { PrecisionEye } from "@/components/precision-eye";
import { LogoEye } from "@/components/logo-eye";
import { SiteHeader } from "@/components/site-header";
import { loadPublicDoctors } from "@/lib/doctors";
import { administrativeTeam, faq, site } from "./site-data";

const whatsapp = "https://wa.me/" + site.whatsapp + "?text=" + encodeURIComponent("Hola, quisiera solicitar un turno en Clínica de Ojos. Mi nombre es: ");

// El equipo y la agenda salen de Supabase; se recachea cada 5 minutos para que
// los cambios del panel se vean en la web sin volver a desplegar.
export const revalidate = 300;

export default async function Home() {
  const doctors = await loadPublicDoctors();
  return <main><a className="skip" href="#contenido">Saltar al contenido</a>
    <SiteHeader />
    <section id="inicio" className="hero" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow">Clínica de Ojos · San Juan</p><h1 id="hero-title">Más de 50 años cuidando tu visión</h1><p className="lead">Trayectoria, atención especializada y compromiso con la salud visual de cada generación.</p><div className="actions"><a className="button" href="#turnos">Solicitar turno</a><a className="text-link" href="#clinica">Conocer la clínica →</a></div></div><div className="hero-art hero-logo"><LogoEye /><p>Primera clínica oftalmológica<br/>especializada de San Juan</p></div></section>
    <section id="contenido" className="intro section"><div id="clinica"><p className="eyebrow">Una institución pionera</p><h2>Una historia dedicada a cuidar la mirada de los sanjuaninos</h2></div><div className="intro-copy"><p>Clínica de Ojos es una institución histórica de la oftalmología en San Juan, fundada por los doctores Enrique Larrea, Guillermo Sansó, Héctor Raed y Gloria Waisman.</p><p>Con más de cinco décadas de trayectoria, acompañamos a la comunidad con una atención profesional, cercana y centrada en cada persona.</p></div>
      <div className="history-archive"><figure className="plaque-figure"><img src="/placa-historica-clinica-de-ojos.png" alt="Placa histórica de Clínica de Ojos S.R.L., fechada en mayo de 2012"/><figcaption>Placa institucional · San Juan, mayo de 2012</figcaption></figure><div className="history-timeline"><p className="eyebrow">Hitos de nuestra historia</p><h3>Una trayectoria que transformó la oftalmología sanjuanina</h3><ol><li><time>1971</time><p>El 20 de noviembre se inaugura como la primera clínica privada especializada de la provincia, integrada por los Dres. Enrique Larrea, Héctor Raed y Guillermo Sansó.</p></li><li><time>1980–83</time><p>Se incorpora la Dra. Gloria Waisman, se renuevan las instalaciones y se incorpora el primer láser para fotocoagulación. En 1983 se realiza el primer implante intraocular de la provincia en cirugías de cataratas.</p></li><li><time>1997</time><p>Se inician cirugías de cataratas con facoemulsificación. Ese año se incorporan nuevas técnicas de cirugía vitreorretinal y se crea Excimer Laser San Juan para cirugías refractivas.</p></li><li><time>Actualidad</time><p>La clínica suma nuevas generaciones profesionales, entre ellas la Dra. Celia Larrea y el Dr. Mauricio M. Sansó, manteniendo su compromiso con la atención especializada.</p></li></ol></div></div>
      <div className="founders"><p className="eyebrow">Quienes la fundaron</p><figure className="founders-figure"><img src="/fundadores-clinica.png" alt="La Dra. Gloria Waisman, el Dr. Héctor Raed, el Dr. Guillermo Sansó y el Dr. Enrique Larrea, fundadores de Clínica de Ojos"/><figcaption>De izquierda a derecha: Dra. Gloria Waisman · Dr. Héctor Raed · Dr. Guillermo Sansó · Dr. Enrique Larrea</figcaption></figure></div></section>
    <section className="stats" aria-label="Indicadores institucionales"><div><strong>+50</strong><span>años de trayectoria</span></div><div className="stat-text"><strong>Clínica pionera</strong><span>en San Juan</span></div><div><strong>{String(doctors.length).padStart(2, "0")}</strong><span>profesionales en el equipo actual</span></div><div><strong>100%</strong><span>atención oftalmológica especializada</span></div></section>
    <section id="profesionales" className="section doctors"><div className="section-heading"><div><p className="eyebrow">Equipo médico</p><h2>Profesionales de Clínica de Ojos</h2></div><p>Consultá por disponibilidad y turnos desde la solicitud online o por WhatsApp.</p></div><div className="doctor-grid">{doctors.map((doctor, index) => <article className="doctor" key={doctor.name}><div className="portrait" role="img" aria-label={"Espacio reservado para la foto de " + doctor.name}><span>{doctor.name.startsWith("Dra") ? "Dra" : "Dr"}</span><i>{String(index + 1).padStart(2, "0")}</i></div><p>{doctor.role}</p><h3>{doctor.name}</h3><small className="doctor-schedule">{doctor.schedule}</small><a href="#turnos">Solicitar turno →</a></article>)}</div></section>
    <section id="administracion" className="section admin-team"><div className="section-heading"><div><p className="eyebrow">Equipo administrativo</p><h2>Quienes te acompañan en la gestión</h2></div><p>Administración, coberturas y atención al paciente de Clínica de Ojos.</p></div><div className="admin-grid">{administrativeTeam.map((member) => <article key={member.name}><div className="admin-photo" role="img" aria-label={"Espacio reservado para la foto de " + member.name}>{member.name.slice(0, 1)}<i>Foto</i></div><p>{member.role}</p><h3>{member.name}</h3></article>)}</div></section>
    <section id="prestaciones" className="service-section"><div><p className="eyebrow">Prestaciones</p><h2>Atención oftalmológica con orientación clara</h2><p>Consultanos para conocer las prestaciones disponibles, estudios y requisitos de cobertura.</p><a className="button button-light" href={whatsapp} target="_blank" rel="noreferrer">Consultar por WhatsApp</a></div><PrecisionEye /></section>
    <section id="turnos" className="appointment"><div><p className="eyebrow">Solicitá tu turno</p><h2>Coordiná tu consulta</h2><p>Registrá tu preferencia en seis pasos. La clínica verificará la disponibilidad antes de confirmar el turno.</p><p className="tiny">No solicitamos diagnósticos ni información clínica sensible.</p></div><AppointmentWizard doctors={doctors} /></section>
    <section id="preguntas" className="section faq"><h2>Preguntas frecuentes</h2><div>{faq.map(item => <details key={item.q}><summary>{item.q}<span>+</span></summary><p>{item.a}</p></details>)}</div></section>
    <section id="contacto" className="contact section"><div><p className="eyebrow">Contacto</p><h2>Estamos para orientarte</h2><address><b>Clínica de Ojos S.R.L.</b><br/>General Mariano Acha 641 Sur<br/>Ciudad de San Juan, San Juan, Argentina</address><a className="contact-phone" href={whatsapp} target="_blank" rel="noreferrer">WhatsApp: +54 9 264 670-8422</a><p className="pending">Horario de atención: lunes a viernes, de 8:30 a 19:30.</p></div><div className="map"><iframe title="Ubicación de Clínica de Ojos" src="https://www.google.com/maps?q=General%20Mariano%20Acha%20641%20Sur%2C%20San%20Juan%2C%20Argentina&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div></section>
    <footer><div className="footer-brand"><img src="/logo-clinica-de-ojos.png" alt="Clínica de Ojos"/><p>Más de 50 años con la mirada puesta en el futuro.</p></div><div><a href="#clinica">La clínica</a><a href="#profesionales">Profesionales</a><a href="#turnos">Solicitar turno</a></div><div><a href={site.instagram} target="_blank" rel="noreferrer">Instagram</a><a href="#contacto">Contacto</a><a href="#preguntas">Información médica</a></div><div className="footer-bottom"><p className="copyright">© {new Date().getFullYear()} Clínica de Ojos S.R.L.</p><a className="powered-by" href="https://sanjuania.com.ar" target="_blank" rel="noreferrer">Powered by IA San Juan</a></div></footer><a className="floating-wa" href="#turnos" aria-label="Ir a solicitar un turno"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><rect x="3" y="5" width="18" height="16" rx="2.5"/><path d="M8 3v4M16 3v4M3 11h18"/></svg><span>Solicitar turno</span></a>
  </main>;
}
